"""empty message

Revision ID: 5e0cce21bbc3
Revises: 0129b2c8ddef
Create Date: 2025-11-17 00:45:11.045052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0cce21bbc3'
down_revision = '0129b2c8ddef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva_mesas',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], ),
    sa.PrimaryKeyConstraint('reserva_id', 'mesa_id')
    )
    with op.batch_alter_table('mesa', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mesa_reserva_id_fkey'), type_='foreignkey')
        batch_op.drop_column('reserva_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserva_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('mesa_reserva_id_fkey'), 'reserva', ['reserva_id'], ['id'])

    op.drop_table('reserva_mesas')
    # ### end Alembic commands ###
