"""Add is_active column to Layout table

Revision ID: d5b13332d340
Revises: 0f405f7b5782
Create Date: 2025-11-20 21:56:48.093694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b13332d340'
down_revision = '0f405f7b5782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
