"""empty message

Revision ID: e7092442e3cf
Revises: 02b4b829cf73
Create Date: 2025-11-16 18:31:41.948029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7092442e3cf'
down_revision = '02b4b829cf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.alter_column('width_px',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('height_px',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('width_m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('height_m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('m_to_px',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('mesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('coords_mesa_pixeles', postgresql.ARRAY(sa.Float()), nullable=True))
        batch_op.add_column(sa.Column('coords_mesa_metros', postgresql.ARRAY(sa.Float()), nullable=True))
        batch_op.alter_column('id_str',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('pos_y_m')
        batch_op.drop_column('pos_x_m')
        batch_op.drop_column('width_m')
        batch_op.drop_column('height_m')

    with op.batch_alter_table('silla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('coords_pixeles', postgresql.ARRAY(sa.Float()), nullable=True))
        batch_op.add_column(sa.Column('coords_metros', postgresql.ARRAY(sa.Float()), nullable=True))
        batch_op.alter_column('id_str',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('pos_y_m')
        batch_op.drop_column('pos_x_m')
        batch_op.drop_column('width_m')
        batch_op.drop_column('height_m')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('silla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('width_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pos_x_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pos_y_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('id_str',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('coords_metros')
        batch_op.drop_column('coords_pixeles')
        batch_op.drop_column('tipo')

    with op.batch_alter_table('mesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('width_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pos_x_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pos_y_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('id_str',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('coords_mesa_metros')
        batch_op.drop_column('coords_mesa_pixeles')
        batch_op.drop_column('tipo')

    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('m_to_px',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('height_m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('width_m',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('height_px',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('width_px',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
