"""Add layout_id to Reserva table

Revision ID: f3c81b24a87b
Revises: d5b13332d340
Create Date: 2025-11-20 22:31:50.614729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c81b24a87b'
down_revision = 'd5b13332d340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'layout', ['layout_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('layout_id')

    # ### end Alembic commands ###
